### ISSUE TITLE
Would you like to move in to the fisherman org?

### ISSUE THREAD

**Issue by bucaran** [fisherman/autoenvstack#1]
Hi @hutenosa

fisherman just turn 2.0 and some things changed, namely, we don't depend on an index anymore. In order to improve discoverability I am trying to reach out to some of plugin authors and ask them if they would like to join the fisherman org and bring their plugins / themes with them.

How does that sound?

**Comment by hutenosa** [comment]
Sounds good for me, how can I contribute?

**Comment by hutenosa** [comment]
Done!
