### ISSUE TITLE
Source at terminal start

### ISSUE THREAD

**Issue by mchwalisz** [fisherman/autoenvstack#3]
The environment variables are not sourced while starting the terminal in a given working directory.

Like: `terminator --working-directory ~/Code` would not source `.env.fish` file. The workaround is to do `cd ; cd -` but it is kind of annoying.

**Comment by hutenosa** [comment]
Hello @mchwalisz ,

Thanks for reporting the issue. I've just made a fix. Could you confirm it works as expected?
